Update lernplattform.rmd, create 00_setup_*.R scripts
CorrelAid/lernplattform pull request #24
Opened 2023-03-16 09:36 UTC by tbaldenius

Externalise data-related setup code into four scripts that are named according to their purposes for better overview

2023-03-16 20:23 UTC, zeidli commented
Wegen dem Pull-Request, ich habe mit Zoé vor einiger Zeit geschrieben. Sie hat mir mitgeteilt, dass es neue Namen gibt.
Hier die Liste mit Lektionen und Nummern, die sie eigentlich haben sollten:
1 - Kickoff
2 - Datenschutz & -Ethik
3 - Einführung in RStudio
4 - Daten verstehen mit R
5 - Datenimport
6 - Datentransformation
7 - Datenvisualisierung
8 - Grundlagen der Statistik
9 - Reports
10 - Reportautomatisierung
11 - Interaktive Visualisierung
12 - Daten- und Leuchtturmprojekte der Zivilgesellschaft
Sollen wir den Pull-Request zurückziehen und die Benennung ändern oder es so belassen? Für mich wäre es ok es so zu belassen und dann bei einem neuen Push zu ändern.  Entschuldige die späte Info.

2023-03-17 08:30 UTC, tbaldenius commented
Danke für die Info. Denke wir könnten auch jetzt erstmal pullen und dann als separaten Schritt die Namen ändern. Die eine Änderung hat ja nicht unmittelbar mit der anderen zu tun, meine ich.

2023-03-18 09:59 UTC, selinaZitrone requested changes
Ich finde das sieht richtig gut aus :)

Abgesehen von dem Kommentar zu `dplyr::na_if` hatte ich noch eine Überlegung:
Wollen wir den setup R code in ein Unterverzeichnis packen?
Mein Vorschlag wäre: `R/setup/` 
Der `R/` Ordner könnte dann später auch für andere R Skripte verwendet werden.

2023-03-18 09:59 UTC, selinaZitrone commented on 00_setup_modify_data.R
> +df2 <- df_ %>% dplyr::na_if(-99)
Der Code hier funktioniert bei mir nicht. Ich muss es umschreiben zu:

```r
df2 <- df_ %>% mutate(across(where(is.numeric), ~ dplyr::na_if(.x, -99)))
```

Ich glaube das hat mit package-Versionen zu tun. Welche Version von dplyr benutzt ihr damit der Code noch funktioniert?

2023-03-18 10:46 UTC, LtSalt commented
Eine Frage: Gibt es einen Grund, dass die Daten jedesmal neu gezogen und gecleant werden? Aus Nutzer:innen-Perspektive ergibt das ja keinen Sinn und kostet nur Zeit. Falls nicht: Man könnte das doch nur einmal durchführen und die Daten dann direkt als .csv oder .RData ablegen. Die Skripte könnte man in einem Ordner ablegen, der beim Bauen der Seite ignoriert wird.

2023-03-18 12:01 UTC, merged

2023-03-23 17:40 UTC, friep commented
@ZoeWolter : hast du da eine Meinung zu?

2023-03-24 14:02 UTC, ZoeWolter commented
Hm also ich wüsste tatsächlich nicht, was der Grund dafür war, das im Setup jedes Mal neu zu cleanen anstatt die bereinigten Daten irgendwo hinzupacken und die zu laden. Könnte mir vorstellen, dass das einfach dem geschuldet war, dass das aus den einzelnen Lektionen irgendwann ins Setup geschoben wurde. Also können auch gerne die bereinigten Daten irgendwohin packen!